# Generated by Django 5.0.1 on 2025-09-01 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('report', 'Report Generation'), ('insight', 'Insight'), ('coach_prompt', 'Coach Prompt')], max_length=50)),
                ('model', models.CharField(choices=[('gemini-1.5', 'Gemini 1.5'), ('gemini-flash', 'Gemini Flash')], max_length=50)),
                ('token_in', models.IntegerField()),
                ('token_out', models.IntegerField()),
                ('latency_ms', models.IntegerField()),
                ('status', models.CharField(choices=[('ok', 'Success'), ('error', 'Error')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'user'], name='ai_usage_created_94fc68_idx'), models.Index(fields=['user', 'feature'], name='ai_usage_user_id_1d49f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('progress', 'Progress Report'), ('hero', 'Hero Infographic')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='reports_user_id_cd96aa_idx')],
            },
        ),
    ]
