version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_DB=eurekia_db
      - POSTGRES_USER=eurekia_user
      - POSTGRES_PASSWORD=eurekia_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eurekia_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A quanta worker -l info
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data: