# Generated by Django 5.0.1 on 2025-09-01 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('all', 'All Channels'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='all', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='For email only', max_length=255)),
                ('body', models.TextField()),
                ('variables', models.JSONField(default=list, help_text='List of variable names used in template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message_templates',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('opt_in', 'Opt In'), ('opt_out', 'Opt Out')], max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'channel'], name='consent_log_user_id_12cafb_idx')],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20)),
                ('text', models.TextField()),
                ('parsed_intent', models.CharField(choices=[('checkin', 'Check-in'), ('mood', 'Mood'), ('help', 'Help'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('meta_json', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inbound_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'channel'], name='inbound_mes_user_id_fc06e9_idx'), models.Index(fields=['processed', 'created_at'], name='inbound_mes_process_37691a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('template_key', models.CharField(max_length=100)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider_msg_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outbound_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='outbound_me_user_id_e3d1ce_idx'), models.Index(fields=['status', 'created_at'], name='outbound_me_status_81209e_idx')],
            },
        ),
    ]
